<?php
/**
 * @see \Softserve\Seller\Block\Sellers\Form
 */

 $seller = $block->getSeller();
?>
<div class="block review-add">
    <div class="block-title"><strong><?= $escaper->escapeHtml(__('Write Seller Review')) ?></strong></div>
    <div class="block-content">
    <form action="<?= $escaper->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form" data-role="seller-review-form" data-bind="scope: 'review-form'">
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_fields_before') ?>
        <input type="hidden" name="seller_id" id="seller_id" value="<?= $seller->getSellerId()?>" />
        <input type="hidden" name="seller_code" id="seller_code" value="<?= $seller->getCode()?>" />
        <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
            <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
            <span id="input-message-box"></span>
            <fieldset class="field required review-field-ratings">
                <legend class="label"><span><?= $escaper->escapeHtml(__('Your Rating')) ?></span></legend><br/>
                <div class="control">
                    <div class="nested" id="seller-review-table">
                        <?php foreach ($block->getRatings() as $_rating): ?>
                            <div class="field choice review-field-rating">
                                <label class="label" id="<?= $escaper->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?= $escaper->escapeHtml($_rating->getRatingCode()) ?></span></label>
                                <div class="control review-control-vote">
                                <?php $options = $_rating->getOptions();?>
                                <?php $iterator = 1; foreach ($options as $_option): ?>
                                    <input
                                        type="radio"
                                        name="rate"
                                        id="<?= $escaper->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $escaper->escapeHtmlAttr($_option->getValue()) ?>"
                                        value="<?= $escaper->escapeHtmlAttr($_option->getValue()) ?>"
                                        class="radio"
                                        data-validate="{'rating-required':true}"
                                        aria-labelledby="<?= $escaper->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $escaper->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $escaper->escapeHtmlAttr($_option->getValue()) ?>_label" />
                                    <label
                                        class="rating-<?= $escaper->escapeHtmlAttr($iterator) ?>"
                                        for="<?= $escaper->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $escaper->escapeHtmlAttr($_option->getValue()) ?>"
                                        title="<?= $escaper->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
                                        id="<?= $escaper->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $escaper->escapeHtmlAttr($_option->getValue()) ?>_label">
                                        <span><?= $escaper->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?></span>
                                    </label>
                                    <?php $iterator++; ?>
                                <?php endforeach; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </fieldset>
        <?php endif ?>
            <div class="field review-field-title required">
                <label for="title_field" class="label"><span><?= $escaper->escapeHtml(__('Title')) ?></span></label>
                <div class="control">
                    <input type="text" name="title" id="title_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
                </div>
            </div>
            <div class="field review-field-text required">
                <label for="review_field" class="label"><span><?= $escaper->escapeHtml(__('Message')) ?></span></label>
                <div class="control">
                    <textarea name="message" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar review-form-actions">
            <div class="primary actions-primary">
                <button type="submit" class="action submit primary"><span><?= $escaper->escapeHtml(__('Submit Review')) ?></span></button>
            </div>
        </div>
    </form>
    <script type="text/x-magento-init">
    {
        "[data-role=seller-review-form]": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "#review-form": {
            "Magento_Review/js/error-placement": {},
            "Magento_Review/js/validate-review": {},
            "Magento_Review/js/submit-review": {}
        }
    }
    </script>
    </div>
</div>
